version: '2'
services:
  mysql:
    container_name: mysql_test
    restart: always
    image: 'mysql:5.7'
    environment:
      MYSQL_ROOT_PASSWORD: '$$Adm1nRoot'
      MYSQL_USER: 'vagrant'
      MYSQL_PASSWORD: '$$Adm1nVagrant'
      MYSQL_DATABASE: 'mmall'
    volumes:
      - $PWD/data:/var/lib/mysql
    user: "1000:50" # only for linux use mac/windows mount
    ports:
      - "3306:3306"
